import React, { useState } from 'react';
import {
  Footprints,
  Zap,
  Car,
  Utensils,
  Layers,
  Sparkles,
  ExternalLink,
  RotateCcw,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
} from 'lucide-react';
import { Language } from '../types';

interface CarbonFootprintSectionProps {
  lang: Language;
}

export const CarbonFootprintSection: React.FC<CarbonFootprintSectionProps> = ({ lang }) => {
  // Calculator inputs
  const [electricityKwh, setElectricityKwh] = useState(120);
  const [transportType, setTransportType] = useState<'walk' | 'public' | 'car'>('public');
  const [commuteKmDaily, setCommuteKmDaily] = useState(15);
  const [dietType, setDietType] = useState<'meat' | 'balanced' | 'plant'>('balanced');
  const [materialsKgMonth, setMaterialsKgMonth] = useState(8);
  const [materialSource, setMaterialSource] = useState<'virgin' | 'bank' | 'mixed'>('mixed');
  const [studioMachineHours, setStudioMachineHours] = useState(10);

  // Carbon Emission Factors (kg CO2e approx based on Egypt grid & LCA data)
  // Electricity: ~0.48 kg CO2e per kWh in Egypt
  const electricityEmission = electricityKwh * 0.48;

  // Transport: car ~ 0.17 kg/km, public ~ 0.05 kg/km, walk = 0
  const transportFactor = transportType === 'car' ? 0.17 : transportType === 'public' ? 0.05 : 0;
  const transportEmission = commuteKmDaily * 30 * transportFactor;

  // Diet: meat ~ 200 kg/mo, balanced ~ 130 kg/mo, plant ~ 80 kg/mo
  const dietEmission = dietType === 'meat' ? 200 : dietType === 'balanced' ? 130 : 80;

  // Studio materials:
  // Virgin ~ 3.5 kg CO2e/kg, Mixed ~ 1.8, Bank salvaged ~ 0.3
  const matFactor = materialSource === 'virgin' ? 3.5 : materialSource === 'mixed' ? 1.8 : 0.3;
  const materialsEmission = materialsKgMonth * matFactor;

  // Studio machines (laser / 3D printer / kiln avg 1.2 kW * 0.48 kg/kWh)
  const machineEmission = studioMachineHours * 1.2 * 0.48;

  // Total monthly footprint in kg CO2e
  const totalMonthlyKg = Math.round(
    electricityEmission + transportEmission + dietEmission + materialsEmission + machineEmission
  );

  // Equivalent annual footprint in metric tonnes
  const annualTonnes = (totalMonthlyKg * 12) / 1000;

  // Reset form
  const handleReset = () => {
    setElectricityKwh(120);
    setTransportType('public');
    setCommuteKmDaily(15);
    setDietType('balanced');
    setMaterialsKgMonth(8);
    setMaterialSource('mixed');
    setStudioMachineHours(10);
  };

  return (
    <section id="carbon-footprint" className="py-20 bg-white border-b border-gray-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Title and Intro */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#DFF2D8] text-[#2E8B35] text-xs font-black">
            <Footprints className="w-3.5 h-3.5" />
            <span>{lang === 'ar' ? 'الوعي بالانبعاثات' : 'Emissions Awareness'}</span>
          </div>

          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-[#102A43]">
            {lang === 'ar' ? 'اعرف بصمتك الكربونية' : 'Calculate Your Carbon Footprint'}
          </h2>

          <p className="text-base sm:text-lg text-gray-700 font-medium leading-relaxed">
            {lang === 'ar'
              ? 'البصمة الكربونية هي إجمالي كمية غازات الاحتباس الحراري الناتجة عن أفعالك واستهلاكك للخامات والطاقة. كطالب فنون تطبيقية، فإن خاماتك واستوديوهاتك تصنع فارقاً كبيراً!'
              : 'Your carbon footprint is the total greenhouse gases generated by your actions, studio materials, and energy choices.'}
          </p>
        </div>

        {/* 4 Educational Infographic Pillars */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-5 rounded-2xl bg-amber-50/70 border border-amber-200 space-y-2">
            <div className="w-10 h-10 rounded-xl bg-amber-100 flex items-center justify-center text-[#F39A24]">
              <Zap className="w-5 h-5" />
            </div>
            <h4 className="text-base font-extrabold text-[#102A43]">
              {lang === 'ar' ? '⚡ الكهرباء والاستوديو' : '⚡ Electricity & Studio'}
            </h4>
            <p className="text-xs text-gray-600 leading-normal">
              {lang === 'ar'
                ? 'إطفاء أجهزة الإضاءة والشاشات وأفران الخزف المتروكة في وضع الاستعداد يوفر حتى 15% من الانبعاثات.'
                : 'Powering off idle lighting, screens, and kiln standby saves up to 15% studio emissions.'}
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-blue-50/70 border border-blue-200 space-y-2">
            <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center text-[#087EAD]">
              <Car className="w-5 h-5" />
            </div>
            <h4 className="text-base font-extrabold text-[#102A43]">
              {lang === 'ar' ? '🚗 الانتقال للجامعة' : '🚗 Commuting to Campus'}
            </h4>
            <p className="text-xs text-gray-600 leading-normal">
              {lang === 'ar'
                ? 'استخدام القطار أو النقل الجماعي أو مشاركة الركوب لمدينة بنها يقلل بصمتك بنسبة 60% مقارنة بالسيارة الخاصة.'
                : 'Using train or shared carpooling to Benha reduces individual transit emissions by 60%.'}
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-emerald-50/70 border border-emerald-200 space-y-2">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center text-[#2E8B35]">
              <Utensils className="w-5 h-5" />
            </div>
            <h4 className="text-base font-extrabold text-[#102A43]">
              {lang === 'ar' ? '🥗 الغذاء والاستهلاك' : '🥗 Food Choices'}
            </h4>
            <p className="text-xs text-gray-600 leading-normal">
              {lang === 'ar'
                ? 'الاعتماد على وجبات محلية طازجة وزجاجات مياه مستدامة يمنع تراكم آلاف الزجاجات البلاستيكية أسبوعياً.'
                : 'Choosing local seasonal snacks and reusable tumblers eliminates thousands of single-use bottles.'}
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-purple-50/70 border border-purple-200 space-y-2">
            <div className="w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center text-[#6950A1]">
              <Layers className="w-5 h-5" />
            </div>
            <h4 className="text-base font-extrabold text-[#102A43]">
              {lang === 'ar' ? '🛍️ خامات المشاريع والتصنيع' : '🛍️ Project Materials'}
            </h4>
            <p className="text-xs text-gray-600 leading-normal">
              {lang === 'ar'
                ? 'إنقاذ خامات من بنك الكلية يعزل الكربون ويوفر تكلفة تصنيع مواد جديدة من الصفر بنسبة تفوق 80%.'
                : 'Salvaging studio offcuts isolates carbon and avoids high embedded energy of virgin supplies.'}
            </p>
          </div>
        </div>

        {/* Interactive Calculator Box */}
        <div className="bg-[#FFF9ED] rounded-3xl p-6 sm:p-10 border-2 border-[#102A43]/10 shadow-lg">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Input Controls (Left Column) */}
            <div className="lg:col-span-7 space-y-6">
              <div className="flex items-center justify-between border-b border-gray-200/80 pb-3">
                <h3 className="text-xl font-black text-[#102A43]">
                  {lang === 'ar' ? 'حاسبة بصمة طالب الفنون التطبيقية' : 'Applied Arts Student Calculator'}
                </h3>
                <button
                  onClick={handleReset}
                  className="flex items-center gap-1 text-xs font-bold text-gray-500 hover:text-black"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  <span>{lang === 'ar' ? 'إعادة تعيين' : 'Reset'}</span>
                </button>
              </div>

              {/* 1. Electricity */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs sm:text-sm font-bold text-[#102A43]">
                  <span>⚡ {lang === 'ar' ? 'استهلاك الكهرباء الشهري في السكن / المنزل' : 'Monthly Home/Dorm Power'}</span>
                  <span className="text-[#2E8B35] font-extrabold">{electricityKwh} ك.و.س</span>
                </div>
                <input
                  type="range"
                  min="30"
                  max="400"
                  step="10"
                  value={electricityKwh}
                  onChange={(e) => setElectricityKwh(Number(e.target.value))}
                  className="w-full accent-[#2E8B35]"
                />
                <div className="flex justify-between text-[10px] text-gray-400">
                  <span>30 ك.و.س (اقتصادي)</span>
                  <span>400 ك.و.س (مرتفع)</span>
                </div>
              </div>

              {/* 2. Transportation */}
              <div className="space-y-2">
                <label className="block text-xs sm:text-sm font-bold text-[#102A43]">
                  🚗 {lang === 'ar' ? 'طريقة وسيلة الانتقال اليومية إلى كلية الفنون' : 'Daily Commute Method'}
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'walk', labelAr: 'مشي / دراجة', labelEn: 'Walk / Bike' },
                    { id: 'public', labelAr: 'مواصلات عامة / قطار', labelEn: 'Public Transit' },
                    { id: 'car', labelAr: 'سيارة خاصة / تاكسي', labelEn: 'Private Car' },
                  ].map((m) => (
                    <button
                      key={m.id}
                      onClick={() => setTransportType(m.id as any)}
                      className={`p-2.5 rounded-xl border text-xs font-bold transition-all ${
                        transportType === m.id
                          ? 'border-[#087EAD] bg-blue-50 text-[#087EAD]'
                          : 'border-gray-200 bg-white text-gray-600'
                      }`}
                    >
                      {lang === 'ar' ? m.labelAr : m.labelEn}
                    </button>
                  ))}
                </div>
                {transportType !== 'walk' && (
                  <div className="pt-1">
                    <span className="text-xs text-gray-500 font-semibold">
                      المسافة اليومية التقريبية: {commuteKmDaily} كم
                    </span>
                    <input
                      type="range"
                      min="2"
                      max="60"
                      value={commuteKmDaily}
                      onChange={(e) => setCommuteKmDaily(Number(e.target.value))}
                      className="w-full accent-[#087EAD]"
                    />
                  </div>
                )}
              </div>

              {/* 3. Studio Materials Source */}
              <div className="space-y-2">
                <label className="block text-xs sm:text-sm font-bold text-[#102A43]">
                  🎨 {lang === 'ar' ? 'مصدر خامات مشروعاتك في الورش' : 'Studio Material Sourcing'}
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'bank', labelAr: '♻️ بنك الخامات (مستنقذة)', labelEn: 'Salvaged Bank' },
                    { id: 'mixed', labelAr: '🔄 مختلط (جديد + معاد)', labelEn: 'Mixed' },
                    { id: 'virgin', labelAr: '🛒 خامات جديدة بكر بالكامل', labelEn: '100% Virgin' },
                  ].map((s) => (
                    <button
                      key={s.id}
                      onClick={() => setMaterialSource(s.id as any)}
                      className={`p-2.5 rounded-xl border text-xs font-bold transition-all ${
                        materialSource === s.id
                          ? 'border-[#2E8B35] bg-[#DFF2D8] text-[#2E8B35]'
                          : 'border-gray-200 bg-white text-gray-600'
                      }`}
                    >
                      {lang === 'ar' ? s.labelAr : s.labelEn}
                    </button>
                  ))}
                </div>
              </div>

              {/* 4. Studio Fabrication Machine Hours */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs sm:text-sm font-bold text-[#102A43]">
                  <span>
                    ⚙️ {lang === 'ar' ? 'ساعات تشغيل ماكينات الورش شهرياً (ليزر، CNC، 3D)' : 'Monthly Studio Machine Hours'}
                  </span>
                  <span className="text-[#6950A1] font-extrabold">{studioMachineHours} ساعة</span>
                </div>
                <input
                  type="range"
                  min="0"
                  max="40"
                  value={studioMachineHours}
                  onChange={(e) => setStudioMachineHours(Number(e.target.value))}
                  className="w-full accent-[#6950A1]"
                />
              </div>
            </div>

            {/* Live Result Scorecard (Right Column) */}
            <div className="lg:col-span-5 bg-white rounded-3xl p-6 sm:p-8 border-2 border-[#2E8B35]/40 shadow-xl space-y-6">
              <div className="text-center space-y-2">
                <span className="inline-block px-3 py-1 rounded-full text-xs font-extrabold bg-[#DFF2D8] text-[#2E8B35]">
                  {lang === 'ar' ? 'النتيجة التقديرية لبصمتك' : 'Estimated Footprint'}
                </span>
                <div className="text-4xl sm:text-5xl font-black text-[#102A43]">
                  {totalMonthlyKg} <span className="text-base text-gray-500 font-bold">كجم CO2e / شهر</span>
                </div>
                <div className="text-xs font-semibold text-gray-500">
                  {lang === 'ar'
                    ? `ما يعادل تقريباً ${annualTonnes.toFixed(1)} طن متري سنوياً`
                    : `Equivalent to approx ${annualTonnes.toFixed(1)} metric tonnes/year`}
                </div>
              </div>

              {/* Progress Bar / Comparison */}
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs font-bold text-gray-600">
                  <span>{lang === 'ar' ? 'مؤشر كفاءة الطالب:' : 'Student Eco-Index:'}</span>
                  <span
                    className={
                      totalMonthlyKg < 180
                        ? 'text-emerald-600 font-black'
                        : totalMonthlyKg < 280
                        ? 'text-amber-600 font-black'
                        : 'text-red-600 font-black'
                    }
                  >
                    {totalMonthlyKg < 180
                      ? lang === 'ar'
                        ? 'ممتاز وصديق للبيئة 🌱'
                        : 'Eco-Friendly'
                      : totalMonthlyKg < 280
                      ? lang === 'ar'
                        ? 'متوسط - يمكنك التحسين 🔄'
                        : 'Moderate'
                      : lang === 'ar'
                      ? 'مرتفع - راجع اختيارات الخامات ⚠️'
                      : 'High Impact'}
                  </span>
                </div>
                <div className="w-full h-3 rounded-full bg-gray-100 overflow-hidden">
                  <div
                    className={`h-full transition-all duration-500 ${
                      totalMonthlyKg < 180 ? 'bg-[#2E8B35]' : totalMonthlyKg < 280 ? 'bg-[#F39A24]' : 'bg-red-500'
                    }`}
                    style={{ width: `${Math.min(100, (totalMonthlyKg / 400) * 100)}%` }}
                  />
                </div>
              </div>

              {/* Actionable Student Tips */}
              <div className="p-3.5 rounded-2xl bg-[#F8FCF6] border border-[#2E8B35]/30 space-y-1.5">
                <div className="text-xs font-extrabold text-[#2E8B35] flex items-center gap-1.5">
                  <Lightbulb className="w-4 h-4" />
                  <span>{lang === 'ar' ? 'كيف تخفض 50 كجم CO2 شهرياً؟' : 'Quick Reduction Tip:'}</span>
                </div>
                <p className="text-xs text-gray-700 leading-relaxed font-medium">
                  {lang === 'ar'
                    ? 'اعتمادك على خامات بنك الخامات بدلاً من شراء خامات جديدة يقلل بصمة مشروعك بنسبة تصل إلى 75%! احجز خامتك الآن.'
                    : 'Switching to salvaged bank offcuts slashes your design carbon footprint by up to 75%!'}
                </p>
              </div>

              {/* Mandatory Educational Disclaimer */}
              <div className="p-3 rounded-xl bg-amber-50/70 border border-amber-200/80 flex items-start gap-2 text-[11px] text-amber-900 font-medium">
                <AlertTriangle className="w-4 h-4 text-[#F39A24] shrink-0 mt-0.5" />
                <span>
                  {lang === 'ar'
                    ? 'هذه نتيجة تقديرية تعتمد على البيانات والمعاملات المستخدمة، وتهدف للتوعية وبناء الوعي البيئي لطلاب كلية الفنون التطبيقية.'
                    : 'This is an estimated educational result based on baseline emission factors for awareness.'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Links to External Trusted Carbon Footprint Calculators */}
        <div className="bg-gray-50 rounded-2xl p-6 border border-gray-200 space-y-3">
          <div className="text-sm font-extrabold text-[#102A43]">
            {lang === 'ar' ? 'حاسبات كربون عالمية ومعتمدة للتعمق:' : 'Trusted Global Carbon Calculators:'}
          </div>
          <div className="flex flex-wrap gap-3">
            {[
              { name: 'حاسبة الأمم المتحدة (UN Carbon Offset)', url: 'https://offset.climateneutralnow.org/' },
              { name: 'حاسبة WWF الرسمية للبصمة البيئية', url: 'https://footprint.wwf.org.uk/' },
              { name: 'مؤسسة Carbon Footprint Ltd', url: 'https://www.carbonfootprint.com/calculator.aspx' },
            ].map((link, idx) => (
              <a
                key={idx}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-gray-200 text-xs font-bold text-[#087EAD] hover:bg-blue-50 transition-colors"
              >
                <span>{link.name}</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
